name: Build

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:

    needs: prepare
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [8, 10, 12]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true

    - name: Use node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: lint
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: lint

    - name: build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: test
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test:ci

    - name: Archive Extension
      uses: actions/upload-artifact@v1
      with:
        name: chrome-enterprise-tab-rotate
        path: dist

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ./coverage/lcov.info

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: semantic-release
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
