name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test:ci
      env:
        CI: true

    - name: Archive Extension
      uses: actions/upload-artifact@v1
      with:
        name: chrome-enterprise-tab-rotate
        path: dist

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ./coverage/lcov.info

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          '@semantic-release/git'
          '@semantic-release/changelog'
          'semantic-release-chrome'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}